name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: ${{ github.repository_owner }}
        reponame: 'likecoin-nft-ranking'
        useyarn: true
        token: ${{ secrets.GITHUB_TOKEN }}
